name: simplest_transfer
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - fastai
  - pandas
  - pillow
  - matplotlib
  - jupyter
  - pip
  - timm
  - scikit-learn
  - numpy
  - pytorch
  - torchvision
  - pip:
    - kaggle